name: PlatformIO CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Execute tests
          run: exit 0

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run
      - name: Deploy release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: "kevinhikaruevans/pio-action-test-releases" # ${{ github.repository }}
        run: |
          TAG=$(git describe --tags --abbrev=0)
          TAG=v$(date +%Y%m%d.%H%M%S)
          RELEASE_NAME="Release $TAG"
          gh release create "$TAG" ~/.pio/build/esp32-s3-devkitc-1/firmware.bin --title "$RELEASE_NAME" --notes "Automated release for $TAG"

