name: PlatformIO CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Execute tests
          run: exit 0

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core and CRC32
        run: |
          pip install --upgrade platformio
          sudo apt-get install libarchive-zip-perl

      - name: Build PlatformIO Project
        run: pio run
      
      - name: Deploy release
        env:
          GH_TOKEN: ${{ secrets.SECONDARY_PAT }}

        run: |
          TAG=v$(date +%Y%m%d.%H%M%S)
          RELEASE_NAME="Release $TAG"
          CRC=$(crc32 ".pio/build/esp32-s3-devkitc-1/firmware.bin")
          gh release create "$TAG" release.bin --title "$RELEASE_NAME" --notes "CRC=$CRC - Automated release for $TAG" -R "kevinhikaruevans/pio-action-test-releases" 
        
        # TODO: append crc32 to binary name

