name: PlatformIO CI

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers the workflow on any tag that matches the pattern vX.X.X

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run
  
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Execute tests
          run: exit 0
  
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    # TODO: choose branch name
    if: github.ref == 'refs/heads/main' 
    steps:
        - name: Deploy release
          env:
            GH_TOKEN: ${{ github.token }}
            GH_REPO: "kevinhikaruevans/pio-action-test-releases" # ${{ github.repository }}
          run: |
            TAG=$(git describe --tags --abbrev=0)
            RELEASE_NAME="Release $TAG"
            gh release create "$TAG" ~/.pio/build/esp32-s3-devkitc-1/firmware.bin --title "$RELEASE_NAME" --notes "Automated release for $TAG"

          # gh release edit "${{ needs.release.outputs.tag }}" --draft=false